version: '3.3'
services:
  web:
    container_name: my-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always